field: 92346b8b-4c62-47cc-b648-0a442ed0324e # Lab Member Research Topic
fieldLayouts:
  2c8039a4-8a1d-40af-9f96-99369996b8e3:
    tabs:
      -
        elements:
          -
            fieldUid: 669fec18-48e6-45a2-b968-5f31b47ba5e8 # Topic
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  669fec18-48e6-45a2-b968-5f31b47ba5e8: # Topic
    columnSuffix: null
    contentColumnType: string(800)
    fieldGroup: null
    handle: topic
    instructions: 'Enter your topic.'
    name: Topic
    searchable: false
    settings:
      byteLimit: null
      charLimit: 200
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: appliedStudyTopic
name: 'Applied Study Topic'
sortOrder: 5
