field: 0f7518d6-3de5-4e47-9259-b49468417a33 # Comment
fieldLayouts:
  b57360e4-5065-430c-8627-4f0e1c84c470:
    tabs:
      -
        elements:
          -
            fieldUid: 3d2775f0-4784-4cf2-b07b-3566f9385ed6 # Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 806d4716-38cb-4541-a1d3-157625900a31 # Comment Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  3d2775f0-4784-4cf2-b07b-3566f9385ed6: # Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: commentName
    instructions: 'Add the name of the responding publication.'
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  806d4716-38cb-4541-a1d3-157625900a31: # Comment Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: commentLink
    instructions: 'Provide a link (or DOI) to the responding publication.'
    name: 'Comment Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: comment
name: Comment
sortOrder: 1
