field: c26b39d7-adb1-40b6-8b29-54344ee41b21 # Abstract
fieldLayouts:
  c2ea414d-3f3b-4542-bec7-cf12b72ad957:
    tabs:
      -
        elements:
          -
            fieldUid: 9cdd0692-b868-4b1c-a65f-40af7dfff3ba # List Item Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a2f5a57-27e4-4a54-864d-371675912777 # List Item Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5a2f5a57-27e4-4a54-864d-371675912777: # List Item Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: listItemText
    instructions: ''
    name: 'List Item Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9cdd0692-b868-4b1c-a65f-40af7dfff3ba: # List Item Number
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: listItemNumber
    instructions: ''
    name: 'List Item Number'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: listItem
name: 'List Item'
sortOrder: 3
