field: 92346b8b-4c62-47cc-b648-0a442ed0324e # Lab Member Research Topic
fieldLayouts:
  a6e8e961-1e20-4d6c-b827-40bc6b2fd4ba:
    tabs:
      -
        elements:
          -
            fieldUid: 84e570b4-09f8-4dbd-9548-5442ceea6cb4 # Topic
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  84e570b4-09f8-4dbd-9548-5442ceea6cb4: # Topic
    columnSuffix: null
    contentColumnType: string(800)
    fieldGroup: null
    handle: topic
    instructions: 'Enter your topic.'
    name: Topic
    searchable: false
    settings:
      byteLimit: null
      charLimit: 200
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mastersTopic
name: 'Master''s Topic'
sortOrder: 3
