field: 777ccf12-c571-4f11-b650-31b24ab49244 # Authors
fieldLayouts:
  afe24668-be45-4880-9bbd-bd279eb6d337:
    tabs:
      -
        elements:
          -
            fieldUid: dfcff989-694b-4ab2-ba1f-deb34bc4d8e1 # Author Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  dfcff989-694b-4ab2-ba1f-deb34bc4d8e1: # Author Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: authorName
    instructions: "Please add an non-lab member Author Name formatted like:\r\nFirst Initial. Second Initial. . . . Last Name"
    name: 'Author Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Author Name (First initial. Last Name)'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: nonLabMember
name: 'Non-Lab Member'
sortOrder: 2
