field: f5bfacb7-5364-4f09-8f5c-8da4fc51e7b0 # Project Introduction
fieldLayouts:
  0b13f3e4-8db9-425c-9b0c-e33e2feaa806:
    tabs:
      -
        elements:
          -
            fieldUid: aa875c59-c756-45c2-a784-fc7243b7c7cd # Paragraph Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  aa875c59-c756-45c2-a784-fc7243b7c7cd: # Paragraph Text
    columnSuffix: fhzllbpx
    contentColumnType: text
    fieldGroup: null
    handle: paragraphText
    instructions: 'Please add paragraph text for your introduction'
    name: 'Paragraph Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
