field: af56ec45-135f-4dee-89cd-cf00fdcea897 # Field Site Introduction
fieldLayouts:
  b96fb9c9-4944-4882-b493-7b9a3123adb9:
    tabs:
      -
        elements:
          -
            fieldUid: 0e164ba4-3501-4b62-9d6d-b5db8439eb9e # Paragraph Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e164ba4-3501-4b62-9d6d-b5db8439eb9e: # Paragraph Text
    columnSuffix: sgzjupim
    contentColumnType: text
    fieldGroup: null
    handle: paragraphText
    instructions: 'Add a paragraph.'
    name: 'Paragraph Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
