field: 1cb6f08b-efbd-4a8d-846d-06c7b904a894 # Detailed Description
fieldLayouts:
  d892fc1a-7e86-4d8d-9cd0-469f56ae5402:
    tabs:
      -
        elements:
          -
            fieldUid: 36c73ff4-c39e-4184-a167-5a99c29dd337 # Paragraph Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  36c73ff4-c39e-4184-a167-5a99c29dd337: # Paragraph Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: paragraphText
    instructions: 'Please add some paragraph text.'
    name: 'Paragraph Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
