field: 1cb6f08b-efbd-4a8d-846d-06c7b904a894 # Detailed Description
fieldLayouts:
  53a2b539-dc98-4e13-ad20-bb081eb13f1a:
    tabs:
      -
        elements:
          -
            fieldUid: 2e06ab0d-7c61-424c-b2cf-d15cd153f7be # Subheader Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2e06ab0d-7c61-424c-b2cf-d15cd153f7be: # Subheader Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subheaderText
    instructions: 'Please add a subheader, if you would like.'
    name: 'Subheader Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subheader
name: Subheader
sortOrder: 1
