field: af56ec45-135f-4dee-89cd-cf00fdcea897 # Field Site Introduction
fieldLayouts:
  fd8bbfa2-640a-4eb2-a1e3-66525f1872ce:
    tabs:
      -
        elements:
          -
            fieldUid: 2c055fe1-39f1-48be-bc4f-bd268c972c15 # Subheader Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2c055fe1-39f1-48be-bc4f-bd268c972c15: # Subheader Text
    columnSuffix: wnjfezst
    contentColumnType: text
    fieldGroup: null
    handle: subheaderText
    instructions: 'Add a header'
    name: 'Subheader Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subheader
name: Subheader
sortOrder: 1
