field: f5bfacb7-5364-4f09-8f5c-8da4fc51e7b0 # Project Introduction
fieldLayouts:
  989cb9d0-759f-4153-91f3-b846f9e35156:
    tabs:
      -
        elements:
          -
            fieldUid: 9cadba58-6635-4645-92c8-3aa83b71487f # Subheader Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9cadba58-6635-4645-92c8-3aa83b71487f: # Subheader Text
    columnSuffix: utgpxkqz
    contentColumnType: text
    fieldGroup: null
    handle: subheaderText
    instructions: 'Please add a subheader, if you would like.'
    name: 'Subheader Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subheader
name: Subheader
sortOrder: 1
