field: 1cb6f08b-efbd-4a8d-846d-06c7b904a894 # Detailed Description
fieldLayouts:
  c8bfaae9-e1e7-411b-854a-b02fbc506357:
    tabs:
      -
        elements:
          -
            fieldUid: 2abab7a6-ba02-4526-82b7-8242ed182af1 # Subheader
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac9811cb-bdd9-4929-a11a-a585b04df8b4 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 821b5002-3b31-4c59-9d58-a2e2df1dba37 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2abab7a6-ba02-4526-82b7-8242ed182af1: # Subheader
    columnSuffix: xdszhqgy
    contentColumnType: text
    fieldGroup: null
    handle: subheader
    instructions: 'Please add a subheader, if you would like.'
    name: Subheader
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  821b5002-3b31-4c59-9d58-a2e2df1dba37: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Please add an image to accompany your text.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
      defaultUploadLocationSubpath: 'projects/{owner.entry.title}'
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ac9811cb-bdd9-4929-a11a-a585b04df8b4: # Paragraph
    columnSuffix: obtwjfqd
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: 'Please add a paragraph.'
    name: Paragraph
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textWithAccompanyingImage
name: 'Text with Accompanying Image'
sortOrder: 4
