field: faf3afa8-b0f9-4fe0-ba37-04ba4ddc68bc # Social Media Links
fieldLayouts:
  5ded86f9-3d52-424d-b20b-8029c421e2a6:
    tabs:
      -
        elements:
          -
            fieldUid: 38a30e07-a6ba-40f7-baef-53dcf152cc6e # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  38a30e07-a6ba-40f7-baef-53dcf152cc6e: # Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: smLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: twitter
name: Twitter
sortOrder: 1
