fieldLayouts:
  2af97c03-0e22-4cc4-b0aa-1d3732c027b0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e6e48943-71b9-4098-a049-cdd8937160fe # Publication Year
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 24f1f6f9-ea15-4f63-afde-6af30947264c # DOI
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: c2f3d0bd-772c-4ae3-a105-4d9399c63058 # Volume
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 15f83211-048a-4852-840d-b48e53ef1fd0 # Issue
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 2f740af2-bdc8-4afa-81e5-2ffab89d65aa # Page Range
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 777ccf12-c571-4f11-b650-31b24ab49244 # Authors
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c775b4e8-319c-4620-886c-e4a597fe47b7 # Journal Name
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e045d973-eb94-4cae-9f6b-95c34a1e222e # Book Chapter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0a4d397c-10ba-4a23-95dd-413002883b3f # Publication Cover Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c26b39d7-adb1-40b6-8b29-54344ee41b21 # Abstract
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0f7518d6-3de5-4e47-9259-b49468417a33 # Comment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: publicationEntry
hasTitleField: true
name: 'Publication Entry'
section: 81c8fc25-7c91-4551-bbf2-2e45dcd3c72d # Publication
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
