defaultPlacement: end
fieldLayouts:
  3d321d51-9796-4820-ba6e-951d8967e280:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pastMemberCategory
name: 'Past Member Category'
siteSettings:
  c7ed12fe-7739-44e3-accd-f279f495d152: # banzi-lab
    hasUrls: true
    template: null
    uriFormat: 'past-member-category/{slug}'
structure:
  maxLevels: 1
  uid: 04d9f19e-10b6-4317-b20e-bddbaa7909fa
