columnSuffix: null
contentColumnType: string
fieldGroup: 2528f6a3-ba6d-407c-bd7b-98950fc26ca5 # Publication
handle: authors
instructions: 'Please add all authors on the publication'
name: Authors
searchable: false
settings:
  contentTable: '{{%matrixcontent_authors}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
