columnSuffix: null
contentColumnType: string
fieldGroup: 5a459a8a-83ed-4cb0-a0b2-fa9f83ab144f # Project
handle: contributors
instructions: ''
name: 'Contributors '
searchable: false
settings:
  contentTable: '{{%matrixcontent_contributors}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
