columnSuffix: null
contentColumnType: string
fieldGroup: e8cbc24d-b6e1-4380-8372-151d82625c0d # Lab Member
handle: cv
instructions: 'If you would like, please add a CV by uploading a file, or supplying a link.'
name: CV
searchable: false
settings:
  contentTable: '{{%matrixcontent_cv}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
