columnSuffix: mpliicwi
contentColumnType: smallint(4)
fieldGroup: 7179d995-15f8-40c5-8785-7f76d74918b3 # Past Lab Members
handle: endYear
instructions: 'When did they leave the lab?'
name: 'End Year'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 2999
  min: 1900
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
