columnSuffix: null
contentColumnType: string
fieldGroup: 3dc3c38e-60a7-412d-95ca-fc02ead5f8b7 # Field Site
handle: fieldSiteBackgroundImage
instructions: "Please add a background image for your field site.\r\n\r\nEither choose an existing asset, or upload a new one.\r\nThis image is best suited for images with ~16:9 aspect ratios."
name: 'Field Site Background Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  defaultUploadLocationSubpath: 'fieldsites/{owner.slug}/backgroundImage'
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
