columnSuffix: null
contentColumnType: string
fieldGroup: e8cbc24d-b6e1-4380-8372-151d82625c0d # Lab Member
handle: labMemberProfilePicture
instructions: ''
name: 'Lab Member Profile Picture'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  defaultUploadLocationSubpath: 'About/{slug}/profilePicture'
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
