columnSuffix: xfqudmnu
contentColumnType: string(68)
fieldGroup: 2528f6a3-ba6d-407c-bd7b-98950fc26ca5 # Publication
handle: pageRange
instructions: " Add the page range for your publication, if you know it.\r\n\r\ne.g. 14-31"
name: 'Page Range'
searchable: false
settings:
  byteLimit: null
  charLimit: 17
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 14-31
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
