columnSuffix: yibtkbba
contentColumnType: text
fieldGroup: e8cbc24d-b6e1-4380-8372-151d82625c0d # Lab Member
handle: preferredCitationName
instructions: 'If the name appearing in your publication citations differs from your first initial followed by your last name, please add it below. (For example, Henzi, P. is cited as Henzi, S. P.) '
name: 'Preferred Citation Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Henzi, S. P.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
