columnSuffix: null
contentColumnType: string
fieldGroup: 2528f6a3-ba6d-407c-bd7b-98950fc26ca5 # Publication
handle: publicationCoverImage
instructions: "Please upload the cover for the volume/issue for the publication. \r\n\r\nIf no cover is provided here, then the default cover for the Journal will be used, if applicable."
name: 'Publication Cover Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  defaultUploadLocationSubpath: 'publications/{entry.title}/covers/{entry.volume}/{entry.issue}'
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e6732067-02ef-47db-8371-405b77fee1f6' # Images
  singleUploadLocationSubpath: 'publications/{journalName.first}/covers/{slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
