columnSuffix: foxhnhff
contentColumnType: string(255)
fieldGroup: e8cbc24d-b6e1-4380-8372-151d82625c0d # Lab Member
handle: researchGateLink
instructions: ''
name: 'Research Gate Link'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
