columnSuffix: null
contentColumnType: string
fieldGroup: e8cbc24d-b6e1-4380-8372-151d82625c0d # Lab Member
handle: socialMediaLinks
instructions: 'If you would like to add a link to your social media, add it below.'
name: 'Social Media Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmedialinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
