columnSuffix: yzkkfoax
contentColumnType: integer(10)
fieldGroup: 2528f6a3-ba6d-407c-bd7b-98950fc26ca5 # Publication
handle: volume
instructions: 'Please add the volume of the Journal'
name: Volume
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: 'Volume: '
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
