defaultPlacement: end
enableVersioning: true
handle: project
name: Project
propagationMethod: all
siteSettings:
  c7ed12fe-7739-44e3-accd-f279f495d152: # banzi-lab
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 0b239fdd-1dc5-4bda-b3f7-cb53114eaf00
type: structure
