defaultPlacement: beginning
enableVersioning: true
handle: publication
name: Publication
propagationMethod: all
siteSettings:
  c7ed12fe-7739-44e3-accd-f279f495d152: # banzi-lab
    enabledByDefault: true
    hasUrls: true
    template: modules/_publicationsComponent.twig
    uriFormat: 'publications#{slug}'
structure:
  maxLevels: 1
  uid: 8146022d-9e7b-44c3-9814-600dbc3de24b
type: structure
